<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-PF2RVK7E" failures="1" tests="3" name="Test2" time="0.077" errors="0" timestamp="2024-06-12T13:25:46 IST">
  <testcase classname="ListernerTest" name="test1" time="0.018"/>
  <testcase classname="ListernerTest" name="test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at ListernerTest.test2(ListernerTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="ListernerTest" name="test3" time="0.002">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test2 -->
